language: node_js

node_js:
- 8

before_install:
- yarn global add greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update

script:
- yarn run lint
- yarn run lint-dts
- yarn run build
- yarn run test-utils -- --ci --verbose --coverage
- yarn run test -- --ci --testPathPattern='/tests/ramda-tests.ts' --verbose=false
- yarn run test -- --ci --testPathPattern='/tests/[a-z_]+.ts'
- yarn run remap -- --check --list-different

after_success:
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/deploy.sh; fi

after_script:
- greenkeeper-lockfile-upload

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true

notifications:
  email: false
