language: node_js

node_js:
- stable

script:
- yarn run lint
- yarn run build-check
- yarn run remap-check
- yarn run test-utils -- --verbose --coverage
- yarn run test -- --verbose
- yarn run test-actual -- --verbose -u

after_success:
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/deploy.sh; fi

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true

notifications:
  email: false
